repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/biomejs/pre-commit
    rev: "v2.2.4"
    hooks:
      - id: biome-check

  - repo: local
    hooks:
      - id: mix-precommit
        name: "mix precommit"
        entry: mix precommit
        language: system
        pass_filenames: false
        files: \.ex$
