version: "3.2"
services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
volumes:
  pgdata:
